SELECT A.AUTHOR_ID
, B.AUTHOR_NAME
, A.CATEGORY
, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK A, AUTHOR B, BOOK_SALES C
WHERE A.AUTHOR_ID = B.AUTHOR_ID
AND A.BOOK_ID = C.BOOK_ID
AND TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
GROUP BY  A.AUTHOR_ID
        , B.AUTHOR_NAME
        , A.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC