SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR
    , TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH
    , A.GENDER AS GENDER
    , COUNT(DISTINCT(B.USER_ID)) AS USERS
FROM USER_INFO A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
GROUP BY TO_CHAR(SALES_DATE, 'YYYY')
    , TO_NUMBER(TO_CHAR(SALES_DATE, 'MM'))
    , A.GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;