SELECT DISTINCT A.CAR_ID
     , NVL(AVAILABILITY, '대여 가능') AS "AVAILABILITY"
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
  LEFT JOIN (
              SELECT CAR_ID, '대여중' AS "AVAILABILITY"
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
               WHERE '20221016' BETWEEN TO_CHAR(START_DATE,'YYYYMMDD') AND TO_CHAR(END_DATE,'YYYYMMDD')
            ) B
    ON A.CAR_ID = B.CAR_ID
 ORDER BY A.CAR_ID DESC