SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH
     , CAR_ID
     , COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
   AND CAR_ID IN (  
                   SELECT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                    WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
                    GROUP BY CAR_ID
                   HAVING COUNT(*) >= 5
                 )
 GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
HAVING COUNT(*) <> 0
 ORDER BY MONTH ASC, CAR_ID DESC